"""预置 NPC，密集覆盖 Lv1-28，天梯匹配时总能找到水平相近的对手"""

NPC_DEFS = [
    # ── Lv1-5 新手区 ──
    {"name": "训练假人", "buddy_species": "robot", "level": 1,
     "str": 5, "agi": 5, "int": 5, "vit": 5, "elo": 800, "skills": []},
    {"name": "迷路指针", "buddy_species": "snail", "level": 2,
     "str": 8, "agi": 6, "int": 5, "vit": 7, "elo": 830, "skills": []},
    {"name": "野生Bug", "buddy_species": "blob", "level": 3,
     "str": 10, "agi": 7, "int": 6, "vit": 8, "elo": 860, "skills": ["heavy_strike"]},
    {"name": "断线风筝", "buddy_species": "duck", "level": 4,
     "str": 7, "agi": 12, "int": 6, "vit": 7, "elo": 890, "skills": ["dodge"]},
    {"name": "流浪字节", "buddy_species": "ghost", "level": 5,
     "str": 12, "agi": 8, "int": 6, "vit": 10, "elo": 920, "skills": ["heavy_strike"]},
    # ── Lv6-10 初级区 ──
    {"name": "溢出精灵", "buddy_species": "axolotl", "level": 6,
     "str": 8, "agi": 10, "int": 12, "vit": 8, "elo": 940, "skills": ["fireball"]},
    {"name": "死循环蜗牛", "buddy_species": "snail", "level": 7,
     "str": 10, "agi": 5, "int": 8, "vit": 15, "elo": 960, "skills": ["block"]},
    {"name": "未初始化猫", "buddy_species": "cat", "level": 8,
     "str": 10, "agi": 16, "int": 8, "vit": 8, "elo": 980, "skills": ["dodge", "combo"]},
    {"name": "空指针幽灵", "buddy_species": "ghost", "level": 9,
     "str": 8, "agi": 12, "int": 16, "vit": 8, "elo": 1000, "skills": ["fireball", "freeze"]},
    {"name": "影子进程", "buddy_species": "cat", "level": 10,
     "str": 8, "agi": 20, "int": 10, "vit": 8, "elo": 1020, "skills": ["dodge", "combo"]},
    # ── Lv11-15 中级区 ──
    {"name": "递归兔子", "buddy_species": "rabbit", "level": 11,
     "str": 12, "agi": 14, "int": 14, "vit": 10, "elo": 1050, "skills": ["combo", "fireball"]},
    {"name": "内存泄漏体", "buddy_species": "blob", "level": 12,
     "str": 15, "agi": 8, "int": 10, "vit": 20, "elo": 1070, "skills": ["block", "thorns"]},
    {"name": "竞态蘑菇", "buddy_species": "mushroom", "level": 13,
     "str": 10, "agi": 10, "int": 20, "vit": 12, "elo": 1090, "skills": ["fireball", "freeze"]},
    {"name": "死锁仙人掌", "buddy_species": "cactus", "level": 14,
     "str": 12, "agi": 8, "int": 12, "vit": 22, "elo": 1110, "skills": ["block", "thorns", "regenerate"]},
    {"name": "守护线程", "buddy_species": "turtle", "level": 15,
     "str": 10, "agi": 6, "int": 12, "vit": 25, "elo": 1130, "skills": ["block", "thorns", "regenerate"]},
    # ── Lv16-20 高级区 ──
    {"name": "协程猎手", "buddy_species": "owl", "level": 16,
     "str": 12, "agi": 22, "int": 14, "vit": 10, "elo": 1150, "skills": ["dodge", "combo", "assassinate"]},
    {"name": "GC收割者", "buddy_species": "octopus", "level": 17,
     "str": 20, "agi": 12, "int": 14, "vit": 14, "elo": 1180, "skills": ["heavy_strike", "armor_break", "berserk"]},
    {"name": "量子水豚", "buddy_species": "capybara", "level": 18,
     "str": 14, "agi": 14, "int": 14, "vit": 20, "elo": 1200, "skills": ["fireball", "block", "regenerate"]},
    {"name": "段错误龙", "buddy_species": "dragon", "level": 19,
     "str": 18, "agi": 14, "int": 20, "vit": 12, "elo": 1220, "skills": ["fireball", "freeze", "berserk"]},
    {"name": "编译之龙", "buddy_species": "dragon", "level": 20,
     "str": 18, "agi": 15, "int": 22, "vit": 15, "elo": 1250, "skills": ["fireball", "freeze", "annihilate"]},
    # ── Lv21-25 精英区 ──
    {"name": "僵尸进程", "buddy_species": "ghost", "level": 21,
     "str": 20, "agi": 18, "int": 16, "vit": 18, "elo": 1280, "skills": ["heavy_strike", "berserk", "regenerate"]},
    {"name": "管道破裂者", "buddy_species": "penguin", "level": 22,
     "str": 16, "agi": 22, "int": 18, "vit": 16, "elo": 1310, "skills": ["combo", "assassinate", "freeze"]},
    {"name": "栈溢出巨兽", "buddy_species": "chonk", "level": 23,
     "str": 24, "agi": 12, "int": 16, "vit": 22, "elo": 1340, "skills": ["heavy_strike", "armor_break", "berserk"]},
    {"name": "内核恐慌", "buddy_species": "goose", "level": 24,
     "str": 18, "agi": 20, "int": 22, "vit": 16, "elo": 1370, "skills": ["annihilate", "assassinate", "dodge"]},
    {"name": "源码圣殿看门人", "buddy_species": "octopus", "level": 25,
     "str": 22, "agi": 20, "int": 25, "vit": 22, "elo": 1400, "skills": ["berserk", "assassinate", "annihilate"]},
    # ── Lv26-28 传说区 ──
    {"name": "Undefined之影", "buddy_species": "ghost", "level": 26,
     "str": 24, "agi": 24, "int": 22, "vit": 22, "elo": 1450, "skills": ["assassinate", "annihilate", "regenerate"]},
    {"name": "零日漏洞", "buddy_species": "robot", "level": 27,
     "str": 25, "agi": 22, "int": 26, "vit": 20, "elo": 1500, "skills": ["berserk", "annihilate", "armor_break"]},
    {"name": "无限递归", "buddy_species": "dragon", "level": 28,
     "str": 26, "agi": 24, "int": 28, "vit": 24, "elo": 1550, "skills": ["berserk", "assassinate", "annihilate"]},
]
